# Generated by Django 5.0.6 on 2024-07-18 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20)),
                ('capital', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
