# Generated by Django 5.0.6 on 2024-06-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videojuego', models.CharField(max_length=20)),
                ('productora', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
    ]
