# Generated by Django 5.0.6 on 2024-07-17 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega3', '0002_videojuego_delete_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
