# Generated by Django 5.0.6 on 2024-07-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=250)),
                ('liga', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
